hydra:
  run:
    dir: ./hydra_sub_pred/${experiment.mission_name}/${experiment.agent}/${rollout.traj_name}/${rollout.from_step_count}/${rollout.policy_model_checkpoint_short}
  job:
    env_set:
      CUDA_VISIBLE_DEVICES: 0

defaults:
  - base_config
  - _self_

model:
  model_name: subgoal_low_policy
  embedding_dim: 1024 
  dirpath: /vision/u/emilyjin/marple_long/final_checkpoints/${experiment.experiment_name}

data: 
  data_level: low
  goal_conditioned: True
  split: train
  
simulator:
  save: False

rollout:
  policy_model_checkpoint_short: ${model.model_name}_${model.embedding_dim}.ckpt
  n_traj_rollout: 1
  inference_type: sample
  id: ${experiment.mission_name}
  rollout_level: ${data.data_level}
  simulator: False
