hydra:
  sweep:
    dir: ./train/${experiment.experiment_name}
    subdir: ${hydra.job.override_dirname}

defaults:
  - _self_
  - base_config

data:
  split: train
  max_atomic_length: 2

dataloader:
  batch_size: 16

trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 10

model:
  embedding_dim: 1024
  vit_dim: 1024
  vit_depth: 16  
  n_checkpoints: 1 

optimizer:
  name: adam
  lr: 1e-4
  weight_decay: 0
  use_lr_scheduler: true
  warmup: 4

wandb:
  project: marple_long_${experiment.experiment_name}
  name: ${experiment.experiment_name}_${hydra.job.num}
  save_dir: ${hydra.sweep.dir}/${hydra.sweep.subdir}

